# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, choices=[('An', 'Android'), ('Py', 'Python Django'), ('BA', 'Business Analyst'), ('HR', 'HR')], max_length=100)),
                ('member', models.BooleanField(default=False)),
                ('experience', models.IntegerField()),
                ('n_attempts', models.IntegerField(null=True)),
                ('result', models.CharField(blank=True, choices=[('p', 'Pass'), ('f', 'fail'), ('w', 'waiting_list')], max_length=100)),
            ],
        ),
    ]
