# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171027_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('An', 'Android'), ('Py', 'Python Django'), ('BA', 'Business Analyst'), ('HR', 'HR')], max_length=100)),
                ('experience', models.CharField(choices=[('F', 'Freshers'), ('O', 'One'), ('T', 'Two'), ('Th', 'Three'), ('th+', 'Three plus')], max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
