# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('Python', 'Python Django'), ('Tester', 'Tester'), ('Business Analyst', 'Business Analyst'), ('HR', 'HR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='department',
            field=models.CharField(choices=[('Android', 'Android'), ('Python', 'Python Django'), ('Tester', 'Tester'), ('Business Analyst', 'Business Analyst'), ('HR', 'HR')], max_length=100),
        ),
    ]
