# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20171030_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(choices=[('0', 'Freshers'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('3+', 'Three plus')], max_length=100),
        ),
    ]
